### ISSUE TITLE
Feature request: Allow to use different directory.

### ISSUE THREAD

**Issue by ghost** [simoniz0r/todo#2]
It would be nice if it's possible to use directory other than `~/.todo`, for example by defining `TODO_DIR` environment variable.

**Comment by simoniz0r** [comment]
Should be simple enough to do.  I'll get on this later today when I have more time.

**Comment by simoniz0r** [comment]
Done!  

To set a custom todo dir, you can either put `TODO_DIR="/path/to/todo_dir"` in your shell's rc file or you can set it when running todo by running `TODO_DIR="/path/to/todo_dir" ./todo.sh`
